import UIKit

// MARK: - Resource bundle access

/// The bundle that holds the SDK's compiled resources (card-network logos, etc.).
///
/// When the SDK is consumed as a Swift Package, `Bundle.module` is generated by
/// SwiftPM and points at `PayOrcSDK_PayOrcSDK.bundle`. The computed property is
/// kept as the single lookup point so resource loading has one place to evolve if
/// the SDK is ever also shipped as a framework / XCFramework.
enum PayOrcBundle {
    static var resources: Bundle { .module }
}

extension UIImage {

    /// Loads an image by name from the PayOrcSDK resource bundle.
    ///
    /// Use this instead of `UIImage(named:)` everywhere inside the SDK — plain
    /// `UIImage(named:)` resolves against the host app's main bundle, which does
    /// not contain the SDK's bundled assets when the SDK is installed via SwiftPM.
    ///
    /// - Parameter payorcNamed: The asset name in `PayOrcMedia.xcassets`
    ///   (e.g. `"visa"`, `"mastercard"`, `"tabby"`).
    convenience init?(payorcNamed name: String) {
        self.init(named: name, in: PayOrcBundle.resources, compatibleWith: nil)
    }
}
